# fly.toml app configuration file generated for backend-dispakan-1 on 2023-07-15T23:42:30+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-dispakan-1"
primary_region = "sin"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
