# fly.toml file generated for dispakanapi on 2023-10-01T19:39:41+07:00

app = "dispakanapi"
kill_timeout = 0
primary_region = "sin"

[env]
  HOST = "0.0.0.0"
  PHX_HOST = "dispakan-api.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
