# fly.toml app configuration file generated for dispakan-api on 2023-09-16T01:56:18+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dispakan-api"
primary_region = "sin"

[env]
PHX_HOST = "dispakan-api.fly.dev"
PORT = "8080"
HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0


